
let kNotificationSigningSuccess = "NotificationSigningSuccess"
let kNotificationLogOutSuccess = "NotificationLogOutSuccess"
let kNotificationSigningFailure = "NotificationSigningFailure"
let kNotificationNeedSignUp = "NotificationNeedSignUp"
let kNotificationFetchFacebookInfoSuccess = "NotificationFetchFacebookInfoSuccess"
let kNotificationFetchKakaoInfoSuccess = "NotificationFetchKakaoInfoSuccess"
let kNotificationFetchAppStoreVersionSuccess = "NotificationFetchAppStoreVersionSuccess"
let kNotificationFetchDeviceInfoSuccess = "NotificationFetchDeviceInfoSuccess"
let kNotificationNetworkStart = "NotificationNetworkStart"
let kNotificationNetworkEnd = "NotificationNetworkEnd"
let kNotificationGuestAuthenticationSuccess = "NotificationGuestAuthenticationSuccess"
let kNotificationFetchTemplateListSuccess = "NotificationFetchTemplateListSuccess"
let kNotificationFetchShopListSuccess = "NotificationFetchShopListSuccess"
let kNotificationFetchProductListSuccess = "NotificationFetchProductListSuccess"
let kNotificationFetchProductSuccess = "NotificationFetchProductSuccess"
let kNotificationPostCartItemSuccess = "NotificationPostCartItemSuccess"
let kNotificationRequestFindingPasswordSuccess = "NotificationRequestFindingPasswordSuccess"
let kNotificationRequestFindingPasswordFailure = "NotificationRequestFindingPasswordFailure"
let kNotificationFetchMyInfoSuccess = "NotificationFetchMyInfoSuccess"
let kNotificationFetchLocationListSuccess = "NotificationFetchLocationListSuccess"
let kNotificationFetchAddressListSuccess = "NotificationFetchAddressListSuccess"
let kNotificationFetchCartListSuccess = "NotificationFetchCartListSuccess"
let kNotificationFetchOrderSuccess = "NotificationFetchOrderSuccess"
let kNotificationValidateAddressSuccess = "NotificationValidateAddressSuccess"

let kNotificationProductDetailImageTapped = "NotificationProductDetailImageTapped"
let kNotificationLocationButtonTapped = "NotificationLocationButtonTapped"
let kNotificationDoAction = "NotificationDoAction"
let kNotificationContentsViewLayouted = "NotificationContentsViewLayouted"
let kNotificationKeyIndex = "NotificationKeyIndex"
let kNotificationKeyIsValid = "NotificationKeyIsValid"
let kNotificationKeyView = "NotificationKeyView"

let kNotificationShowAlert = "NotificationShowAlert"
let kNotificationShowWebView = "NotificationShowWebView"
let kNotificationOrder = "NotificationOrder"
let kNotificationSegueToOption = "NotificationSegueToOption"
let kNotificationKeyProductIds = "NotificationKeyProductIds"
let kNotificationKeyProductId = "NotificationKeyProductId"

let kNotificationAlertKeyMessage = "NotificationAlertKeyMessage"
let kNotificationAlertKeyHasCancel = "NotificationAlertKeyHasCancel"
let kNotificationAlertKeyConfirmationAction = "NotificationAlertKeyConfirmationAction"
let kNotificationAlertKeyCancelAction = "NotificationAlertKeyCancelAction"

let kNotificationKeyFacebookName = "NotificationKeyFacebookName"
let kNotificationKeyFacebookEmail = "NotificationKeyFacebookEmail"
let kNotificationKeyHeight = "NotificationKeyHeight"
let kNotificationKeyTemplateId = "NotificationKeyTemplateId"
let kNotificationKeyContentsId = "NotificationKeyContentsId"

let kNotificationKeyErrorStatusCode = "NotificationKeyErrorStatusCode"

let kNotificationAddressSelected = "NotificationAddressSelected"
let kNotificationKeyAddress = "NotificationKeyAddress"
