
let kNotificationDoAction = "NotificationDoAction"
let kNotificationContentsViewLayouted = "NotificationContentsViewLayouted"
let kNotificationSigningSuccess = "NotificationSigningSuccess"
let kNotificationNeedSignUp = "NotificationNeedSignUp"
let kNotificationFetchFacebookInfoSuccess = "NotificationFetchFacebookInfoSuccess"
let kNotificationFetchKakaoInfoSuccess = "NotificationFetchKakaoInfoSuccess"
let kNotificationNetworkStart = "NotificationNetworkStart"
let kNotificationNetworkEnd = "NotificationNetworkEnd"

let kNotificationKeyFacebookName = "NotificationKeyFacebookName"
let kNotificationKeyFacebookEmail = "NotificationKeyFacebookEmail"
let kNotificationKeyHeight = "NotificationKeyHeight"
let kNotificationKeyTemplateId = "NotificationKeyTemplateId"
let kNotificationKeyContentsId = "NotificationKeyContentsId"