
let kNotificationDoAction = "NotificationDoAction"
let kNotificationContentsViewLayouted = "NotificationContentsViewLayouted"
let kNotificationSigningSuccess = "NotificationSigningSuccess"
let kNotificationSigningFailure = "NotificationSigningFailure"
let kNotificationNeedSignUp = "NotificationNeedSignUp"
let kNotificationFetchFacebookInfoSuccess = "NotificationFetchFacebookInfoSuccess"
let kNotificationFetchKakaoInfoSuccess = "NotificationFetchKakaoInfoSuccess"
let kNotificationNetworkStart = "NotificationNetworkStart"
let kNotificationNetworkEnd = "NotificationNetworkEnd"
let kNotificationGuestAuthenticationSuccess = "NotificationGuestAuthenticationSuccess"
let kNotificationFetchTemplateListSuccess = "NotificationFetchTemplateListSuccess"
let kNotificationRequestFindingPasswordSuccess = "NotificationRequestFindingPasswordSuccess"
let kNotificationRequestFindingPasswordFailure = "NotificationRequestFindingPasswordFailure"

let kNotificationShowAlert = "NotificationShowAlert"
let kNotificationShowWebView = "NotificationShowWebView"

let kNotificationAlertKeyMessage = "NotificationAlertKeyMessage"
let kNotificationAlertKeyHasCancel = "NotificationAlertKeyHasCancel"
let kNotificationAlertKeyConfirmationAction = "NotificationAlertKeyConfirmationAction"
let kNotificationAlertKeyCancelAction = "NotificationAlertKeyCancelAction"

let kNotificationKeyFacebookName = "NotificationKeyFacebookName"
let kNotificationKeyFacebookEmail = "NotificationKeyFacebookEmail"
let kNotificationKeyHeight = "NotificationKeyHeight"
let kNotificationKeyTemplateId = "NotificationKeyTemplateId"
let kNotificationKeyContentsId = "NotificationKeyContentsId"

let kNotificationKeyErrorStatusCode = "NotificationKeyErrorStatusCode"